import React from "react";
import { FaInfoCircle, FaStar, FaBrain, FaRegCheckCircle } from "react-icons/fa";

const OfficerSummary = ({ summary }) => {
  if (!summary) return null;

  return (
    <div className="bg-slate-900/60 border border-slate-800 rounded-xl p-5 shadow-lg flex flex-col h-[500px]">
      
      {/* Header */}
      <div className="flex items-center justify-between border-b border-slate-800 pb-3 mb-4">
        <div className="flex items-center gap-2">
          <FaInfoCircle className="text-blue-400 text-sm" />
          <h2 className="text-xs font-bold text-white uppercase tracking-wider font-mono">
            AI Performance Recommendation
          </h2>
        </div>
        <span className="rounded-full bg-slate-800 px-2.5 py-0.5 font-mono text-[9px] text-slate-400">
          Source: KSP Audit
        </span>
      </div>

      {/* Main content grid */}
      <div className="flex-1 flex flex-col justify-between font-mono text-[10px] leading-normal space-y-4">
        
        {/* Rating and Strengths */}
        <div className="space-y-4">
          <div>
            <span className="text-slate-500 text-[9px] block">PERFORMANCE SCORE:</span>
            <div className="flex items-center gap-2 mt-1.5">
              <span className="text-xl sm:text-2xl font-bold text-white tracking-tight">{summary.rating}</span>
              <div className="flex text-amber-500 text-xs">
                <FaStar /><FaStar /><FaStar /><FaStar /><FaStar />
              </div>
            </div>
          </div>

          <div className="border-t border-slate-850 pt-3">
            <span className="text-slate-500 text-[9px] block">PRIMARY INVESTIGATION STRENGTH:</span>
            <span className="inline-block mt-1.5 px-3 py-1 bg-blue-500/10 text-blue-400 border border-blue-500/20 rounded font-bold uppercase text-[9px] tracking-wide">
              {summary.strongArea}
            </span>
          </div>

          <div className="border-t border-slate-850 pt-3">
            <span className="text-slate-500 text-[9px] block">WORKLOAD CONGESTION RATIO:</span>
            <div className="flex items-center gap-2 mt-1.5">
              <span className={`inline-block h-2 w-2 rounded-full ${
                summary.workloadStatus === "Optimal" ? "bg-emerald-500 animate-pulse" : "bg-amber-500 animate-pulse"
              }`} />
              <span className="text-slate-200 font-bold uppercase tracking-wider">
                {summary.workloadStatus}
              </span>
            </div>
          </div>
        </div>

        {/* AI Recommendation Mock Block */}
        <div className="bg-slate-950/80 border border-slate-850 p-4 rounded-xl flex-1 flex flex-col gap-2 min-h-[140px] justify-center relative overflow-hidden">
          {/* subtle background glow */}
          <div className="absolute -top-10 -left-10 h-20 w-20 bg-blue-500/5 blur-xl rounded-full" />
          
          <div className="flex items-center gap-1.5 text-blue-400 font-bold">
            <FaBrain className="text-xs text-blue-400 animate-pulse" />
            <span className="text-[9px] tracking-wider uppercase">AUTOGENERATED TELEMETRY RECOMMENDATION</span>
          </div>
          <p className="text-slate-400 font-sans text-[10px] leading-relaxed">
            "{summary.aiRecommendation}"
          </p>
        </div>

        {/* Sync details */}
        <div className="border-t border-slate-850 pt-3 flex justify-between items-center text-[8px] text-slate-500">
          <div className="flex items-center gap-1">
            <FaRegCheckCircle className="text-emerald-500" />
            <span>AUDIT METRICS IN SYNC</span>
          </div>
          <span>UPDATED: {summary.lastUpdated}</span>
        </div>

      </div>
    </div>
  );
};

export default OfficerSummary;
